# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
      - bash: echo Build FirstJob
      - bash: echo $(PipelineLevelVariable) 
      - bash: echo $(Build.BuildNumber)
      - bash: echo $(Build.SourceBranchName)
      - bash: echo $(System.DefaultWorkingDirectory)
      - bash: ls -R $(System.DefaultWorkingDirectory)
      - bash: echo $(Build.ArtifactStagingDirectory)
      - bash: ls -R $(Build.ArtifactStagingDirectory)
      - bash: java -version
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: |
           **/*.yaml
           **/*.tf
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - bash: ls -R $(Build.ArtifactStagingDirectory)
  # - job: SecondJob
  #   steps:
  #     - bash: echo Build SecondJob
# - stage: DevDeploy
#   variables:
#     environment: Dev
#   jobs:
#   - job: DevDeployJob
#     steps:
#       - bash: echo Build DevDeployJob
#       - bash: echo $(environment)
# - stage: QADeploy
#   variables:
#     environment: QA
#   jobs:
#   - job: QADeployJob
#     steps:
#       - bash: echo Build QADeployJob
#       - bash: echo $(environment)
# - stage: ProdDeploy   
#   variables:
#     environment: Prod
#   jobs:
#   - job: ProdDeployJob
#     steps:
#       - bash: echo Build ProdDeploy
#       - bash: echo $(environment)